version: '3.9'
    
services:
  nest:
    container_name: nest_app
    image: danywalls/nest-backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    container_name: nest_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    expose:
      - 3306
